1. Maximum of two numbers

In [ ]:
def maximum(a,b):
    if a >=b:
        return a
    else:
        return b
a=2
b=9
print(maximum(a,b))

9


2. python program for finding simple interest

In [ ]:
def simple_interest(p,t,r):
    print("The principle is",p)
    print("The rate period is",t)
    print("The rate of interest is",r)
    si=(p*t*r)/100
    print("The simple interest is",si)
    return si
simple_interest(8,6,8)

The principle is 8
The rate period is 6
The rate of interest is 8
The simple interest is 3.84


3.84

3. Finding compound interest

In [ ]:
def compound_interest(principle,rate,time):
    Amount=principle*(pow((1+rate/1000),time))
    CI= Amount - principle
    print("compound interest is", CI)
compound_interest(10000,10.25,5)

compound interest is 523.1144921003579


4. Print all prime numbers in an interval.

In [ ]:
start = 11
end = 25
for i in range(start , end+1):
    if i>1:
        for j in range(2,i):
            if (i % j == 0):
                break
            else:
                print(i)
                

11
11
11


5. Find area of circle

In [ ]:
def FindArea(r):
    PI=3.142
    return PI*(r*r)
print("area is",FindArea(5))

area is 78.55


6. Sum of squares of first n natural numbers


In [ ]:
def SumSquares(n):
    sm=0
    for i in range(1, n+1):
        sm=sm+(i * i)
    return sm
n=4
print(SumSquares(n))

30


7. cube sum of first n numbers .


In [ ]:
def SumOfCubes(n):
    sum=0
    for i in range(1 , n+1):
        sum += i* i * i
    return sum
n = 5
print(SumOfCubes(n))

225


8. Find the sum of array

In [ ]:
def _sum(arr):
    sum=0
    for i in arr:
        sum=sum+i
    return sum
#arr=[]
arr=[23,45,76,45]
#n=len(arr)
#ans= _sum(arr)
#print("sum of the array is", ans)
print(_sum(arr))

189


9. if a trangles of positive area is possible with given angels

In [ ]:
def isTriangleExists(a,b,c):
    if(a!=0 and b!=0 and c!=0 and (a+b+c) == 180):
        if((a+b)>=c or (b+c)>=a or (c+a)>=b):
            return "yes"
        else:
            return "No"
    else:
        "No"
a,b,c = 50,60,70
print(isTriangleExists(50,60,70))

yes


10. Check if binary representation is palindrome.

In [ ]:
def binaryPalindrome(num):
    binary=bin(num)
    binary=binary[2:]
    return binary == binary[-1::1-1]
if __name = "__main__"
    num=9
    print(binaryPalindrome(num))

SyntaxError: invalid syntax (Temp/ipykernel_7596/1186467807.py, line 5)

##### Patterns 

1. simple pyramid

In [ ]:
def pyramid(n):
    for i in range(0,n):
        for j in range(0, i+1):
            print("*", end=" ")
        print("\r")

n=5
pyramid(n)

* 
* * 
* * * 
* * * * 
* * * * * 


2. simple pyramid using list

In [ ]:
def pyramid(n):
    mylist=[]
    for i in range(1, n+1):
        mylist.append("*")
    print("\n".join(mylist))
n=5
pyramid(n)

*
*
*
*
*


* Find yesterday , today and tomorrow date

In [ ]:
from datetime import datetime 
from datetime import timedelta
presentday = datetime.now()
yesterday = presentday- timedelta(1)
tomorrow = presentday + timedelta(1)
print(" Yesterday =", yesterday.strftime('%d-%m,%y'))
print("Today =", presentday.strftime('%d-%m-%y'))
print("Tomorrow =", tomorrow.strftime('%d-%m-%y'))


 Yesterday = 09-04,22
Today = 10-04-22
Tomorrow = 11-04-22


* Python program to find last date of month

In [ ]:
from datetime import datetime 
import calendar
d = datetime(2022,1,2)
print ("original date is : " +str(d))
res = calendar.monthrange(d.year, d.month)[1]
print("last date of month : "+ str(res))

original date is : 2022-01-02 00:00:00
last date of month : 31


In [ ]:
import datetime
datetime.date(2000, 2, 24) - datetime.timedelta(days=24)

datetime.date(2000, 1, 31)

* To gate month name from month number

In [ ]:
  from datetime import datetime
d = datetime(2022,7,5)
#print(" The original date is : " +str(d))
res= d.strftime("%b")
print(res)
#print(" Month name from date: "+str(res))

Jul


* revese a string without reversing its individuals words

In [ ]:
s="i.like.this.program.very.much"
'.'.join(s.split(".")[::-1])

'much.very.program.this.like.i'

* Using function

In [ ]:
def reverse_string(s):
    return '.'.join(reversed(s.split('.')))

In [ ]:
reverse_string("i.like.this.program.very.muc")

'muc.very.program.this.like.i'

* Using reversed method

In [ ]:
s="i.like.this.program.very.much"
'.'.join(reversed(s.split('.')))

'much.very.program.this.like.i'

* Find the Square of numbers using map function

In [ ]:
def squre(x):
    return x * x
num=[1,2,3,4,5]
Num_squared= map(squre,num)
for num in Num_squared:
        print(num)

1
4
9
16
25


In [2]:
def squre(x):
  return x*x;
num=[2,4,6,8,5]
num_squared=map(squre,num)
for num in num_squared:
  print(num)

4
16
36
64
25


* Number divisible by 3 from tuple using lambda function

In [ ]:
import numpy as np
import pandas as pd
my_tup=(5,32,45,25)
New_tup = tuple(filter(lambda x: (x%3==0),my_tup))
print(New_tup)

(45,)


* 4 by 4 matrix and find diagonal element and sum it

In [ ]:
x=np.array(([[2, 4, 6, 8], 
             [3, 6, 9, -12], 
             [4, 8, 12, 16], 
             [5, -10, 15, 20]]))
x

array([[  2,   4,   6,   8],
       [  3,   6,   9, -12],
       [  4,   8,  12,  16],
       [  5, -10,  15,  20]])

In [ ]:
x.diagonal().sum()

40

* get a len of string without using len function

In [ ]:
a="mvivhjvybnu"
count=0
for i in a:
    count=count+1
print(count)

11


* Replace all elements numpy array to -1

In [ ]:
x= np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[x]=-1
x

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1])

* Count character in string

In [ ]:
df= pd.Series(["feefle","lerond","po45nd","sond"])
df.map(lambda a: len(a))

0    6
1    6
2    6
3    4
dtype: int64

 * Count a charcter occurences 

In [ ]:
from collections import Counter
l="linkedln"
print(Counter(list(l)))

Counter({'l': 2, 'n': 2, 'i': 1, 'k': 1, 'e': 1, 'd': 1})


In [ ]:
s="Linkedin"
s=s.lower()
d={}
for i in s:
    d[i]=0
for i in s:
    d[i]=d[i]+1
print(d)

{'l': 1, 'i': 2, 'n': 2, 'k': 1, 'e': 1, 'd': 1}


How do you print the summation of all the numbers from 1 to 101?

In [ ]:
print(sum(range(1,102)))

5151


Is it possible to construct a Python program that calculates the mean of numbers in a list?

In [ ]:
import numpy as np
list=[34,54,32,54,53,89,59]
print(np.average(list))

53.57142857142857


Reverse a number

In [ ]:
n=23456
print(str(n)[::-1])

65432


Class

In [ ]:
class student:
  def __init__(self,st_name, st_class, st_marks):
    self.st_name = st_name
    self.st_class= st_class
    self.st_marks= 78
s1 = student("sdfg",10,78)
print(s1.st_name)
print(s1.st_class)

sdfg
10


Make a Python script that checks if a given number is prime.

In [ ]:
num=int(input("enter the number"))
if num>1:
  for i in range(2,num):
    if (num%i)==0:
      print(num,"is not prime")
      break
  else:
      print(num,"is prime")
else:
  print(num," is not prime")

enter the number11
11 is prime


 Python program to check if the given string is a palindrome  

In [ ]:
sequence='klmmlk'
reverse=sequence[::-1]
if sequence==reverse:
  print("the sequence is palindrome")
else:
  print("the sequence is not palindrome")

the sequence is palindrome


Using Python/ NumPy, write code to compute percentiles?

In [ ]:
import numpy
array=numpy.array([2,5,4,7,1,2])
percentile=numpy.percentile(array,45)
print(percentile)

2.5


Write a Python program to determine whether a number is binary.

In [ ]:
x=int(input("enter a number "))
if x>0:
  y=x%10
  if x!=0 and x!=1:
    print("number is not binary")
  else:
    print("number is binary")
#k=x//10
#if k==0:
 # print("number is binary")

enter a number 91278176487
number is not binary


Using the Iterative technique, calculate factorial in Python.

In [ ]:
def fectorial(n):
  fact=1
  for i in range(n,0,-1):
    fact = fact * i
  return fact
print(fectorial(5))

120


In [ ]:
def check_anagram(data1, data2):
    data1 = data1.lower()
    data2 = data2.lower()
    if sorted(data1) != sorted(data2):
        return False
    return all(data1[i] != data2[i] for i in range(len(data1)))




In [ ]:
print(check_anagram('buwbwjh','wyguy'))

False


In [ ]:
def findExtraCharacter(strA, strB):
	m1 = {}

	for i in strB:
		if i in m1:
			m1[i] += 1
		else:
			m1[i] = 1

	for i in strA:
		m1[i] -= 1

	for h1 in m1:

		if m1[h1] == 1:
			return h1

if __name__ == "__main__":

	strA = 'abcd'
	strB = 'cbdad'

	print(findExtraCharacter(strA, strB))


d


Write a Python program that removes vowels from a string.

In [ ]:
x=input("enter a name")
v=('a','e','i','o','u')
s=''
for i in x:
  if i.lower() not in v:
    s=s+i
print(s)


enter a nameappalakade
pplkd


In [ ]:
array = [23, 12, 5, 24, 23, 76, 86, 24, 86, 24, 75]
print(array[::-1])

[75, 24, 86, 24, 86, 76, 23, 24, 5, 12, 23]


print the prime numbers between 100 to 200.

In [ ]:
for num in range(100,200):
  if all(num%i !=0 for i in range(2,num)):
    print(num)
  

101
103
107
109
113
127
131
137
139
149
151
157
163
167
173
179
181
191
193
197
199


sort function without using built-in fuction

In [ ]:
l = [64, 25, 12, 22, 11, 1,2,44,3,122, 23, 34]

for i in range(len(l)):
  for j in range(i+1,len(l)):
     if l[i] < l[j]:

        l[i],l[j] = l[j],l[i]
print(l)

[122, 64, 44, 34, 25, 23, 22, 12, 11, 3, 2, 1]


print fibonnacci series.

In [ ]:
def f(n):
  if n== 0:
    return 0
  elif n== 1:
    return 1
  else: 
    return f(n-1)+f(n-2)
for i in range(0,12):
  print(f(i))

0
1
1
2
3
5
8
13
21
34
55
89


Print set of duplicates in the list

In [ ]:
l=[4,5,3,7,2,1,5,4,7,9]
print(set([x for x in l if l.count(x)>1 ]))

{4, 5, 7}


Print the number of words in the sentense

In [ ]:
s= 'pc is a very nice girl'
print(len(s.split()))

6


. Given an array arr[] of n elements, write a Python function to search a given element x in arr[].

In [ ]:
def search(arr,x):
  for i in range(len(arr)):
    if arr[i]==x:
      return i
  print('not in the array')
l=[3,4,6,4,3,8,63,8]
print(search(l,0))


not in the array
None


Write a Python program to join two strings (Hint: using join())

In [ ]:
str='appa lakade'
str1='mahi kaade'
res=" ".join((str, str1))
print(res)

appa lakade mahi kaade


Write a Python program to extract digits from given string.

In [ ]:
l='wvtgvwc342ff45wfew'
res="".join(filter(lambda i: i.isdigit(),l))
res

'34245'

Write a Python program to split strings using newline delimiter

In [ ]:
s='my name is appasaheb'
res=(s.rstrip().split(" "))
res

['my', 'name', 'is', 'appasaheb']

remove duplicates from a list

In [ ]:
string="geeksforgeeks"
p=""
for char in string:
    if char not in p:
        p=p+char
print(p)
k=list("geeksforgeeks")

geksfor


Inheritence Example 

In [ ]:
class parent:
  def __init__ (self, fname, fage):
    self.age= fage
    self.name = fname

  def view(self):
    print(self.age, self.name)

class child(parent):
  def __init__(self, fname, fage):
      parent.__init__(self,fname, fage)
      self.lastname= "edurekha"   

  def view(self):
    print(self.age,self.name,self.lastname)
ob= child(23,'safaer')
ob.view()


safaer 23 edurekha


In [3]:
x = lambda num : 1 if num <= 1 else num*x(num-1)

number = int(input('Enter number: '))

print('%d != %d' %(number, x(number)))

Enter number: 5
5 != 120


In [4]:
from functools import *
output=reduce(lambda x,y:x*y,range(1,6))
print(output)

120


In [19]:
def fact(n):
  if n==0:
    result=1
  else:
    result=n*fact(n-1)
  return result
print(fact(5))

120


In [29]:
l=[1,2,3,4,5]
l2=[10,20,30,40,50]
result=list(map(lambda x,y:x+y,l,l2))

In [30]:
print(result)

[11, 22, 33, 44, 55]


In [31]:
l=[1,2,3,4,5]
l2=[10,20,30,40,50]
result=l+l2

In [32]:
print(result)

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]


In [35]:
result=l.extend(l2)
print(result)

None


In [7]:
# intersection elements in two lists

lst= [34,56,78,90]
lst1= [34,56,32,76]
lst3=[]
for i in lst:
    if i in lst1:
        lst3.append(i)
        
        

In [8]:
lst3

[34, 56]

In [53]:
# reversing the words in string

str1= 'my name is appa'
str2=str1[::-1]
print(str2)
s=str2.split()
s.reverse()
s

appa si eman ym


['ym', 'eman', 'si', 'appa']

In [7]:
print('hello',input(prompt='enter your name'))

enter your name Appa


hello Appa


In [1]:
# how to create pickle object from list

lst=[6,89,4,3,6,]
with open('lst.pickle', 'wb') as file:
    pickle.dump(lst, file)
    

<IPython.core.display.Javascript object>

In [4]:
with open('lst.pickle', 'rb') as file:
    loaded_list = pickle.load(file)

<IPython.core.display.Javascript object>

In [3]:
loaded_list

[6, 89, 4, 3, 6]